services:
  - type: web
    name: zanherb
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      cp .env.example .env || true
      php artisan key:generate
      php artisan migrate --force --seed
      npm install
      npm run build
      php artisan storage:link
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://zanherb.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
